module.exports = [
  { code: 0x01, name: "PASSING_NUMBER", type: "int", size: 4 },
  { code: 0x03, name: "TRANSPONDER", type: "int", size: 4 },
  { code: 0x13, name: "RTC_ID", type: "int", size: 4 },
  { code: 0x04, name: "RTC_TIME", type: "time", size: 8 },
  { code: 0x10, name: "UTC_TIME", type: "time", size: 8 },
  { code: 0x05, name: "STRENGTH", type: "int", size: 2 },
  { code: 0x06, name: "HITS", type: "int", size: 2 },
  { code: 0x08, name: "FLAGS", type: "int", size: 2 },
  { code: 0x0a, name: "TRAN_CODE", type: "string" },
  { code: 0x0e, name: "USER_FLAG", type: "int", size: 4 },
  { code: 0x0f, name: "DRIVER_ID", type: "int", size: 1 },
  { code: 0x14, name: "SPORT", type: "int", size: 1 },
  { code: 0x30, name: "VOLTAGE", type: "int", size: 1 },
  { code: 0x31, name: "TEMPERATURE", type: "int", size: 1 },
];
