# name of your github action
name: CI
# this will help you specify where to run 
on:
  push:
    branches:
    # this will run on the electron branch
      - main

jobs:
build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@master
      with:
        node-version: 16.0
    - name: see directory
      run: ls