# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_on_windows:
    runs-on: windows-2016

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Sentry CLi
        uses: mathieu-bour/setup-sentry-cli@1.2.0
        with:
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }}
          organization: mark-kemper
          project: bmx-clubby-desktop
      - run: |
          node -e "console.log('VERSION=' + require('./package.json').version)"
          node -e "console.log('VERSION=' + require('./package.json').version)" >> $GITHUB_ENV
      - run: echo "${{ env.VERSION }}"
      - run: npm ci
      - run: npm run deploy:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Sentry release
        run: |
          sentry-cli releases new "${{ env.VERSION }}"
          sentry-cli releases set-commits "${{ env.VERSION }}" --auto || true
          sentry-cli releases finalize "${{ env.VERSION }}"
